/**
 * Nectia
 * microservicio de nectia
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ResponseBuscarResponse } from './responseBuscarResponse';

export interface ResponseBuscar { 
    ok?: string;
    response?: ResponseBuscarResponse;
}